apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discounts
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/alpha-hack-program/intelligent-cd-iberia-gitops
    targetRevision: main
    path: discounts/charts
  destination:
    server: https://kubernetes.default.svc
    namespace: discounts-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
