apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "discounts.fullname" . }}-configmap-env-base
data:
  {{- range $key, $value := .Values.configmap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}