apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap-env-base
data:
  application.colour: {{ .Values.configmap.application.colour }}
  application.mode: {{ .Values.configmap.application.mode }}
  application.version: {{ .Values.configmap.application.version }}
  quarkus.log.level: {{ .Values.configmap.quarkus.log.level }}