apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-discounts
spec:
  port:
    targetPort: {{ .Values.route.targetPort }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
  to:
    kind: Service
    name: {{ .Release.Name }}-discounts
    weight: 100