apiVersion: apps/v1
kind: Deployment
metadata:
  name: discounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discounts
  template:
    metadata:
      labels:
        app: discounts
    spec:
      containers:
      - image: quay.io/dseveria/discounts:v1.0.1
        imagePullPolicy: IfNotPresent
        name: discounts
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: discounts-configmap-env-base
data:
  application.colour: black
  application.mode: online
  application.version: v1.0.1
  quarkus.log.level: debug
---
apiVersion: v1
kind: Service
metadata:
  name: discounts
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: discounts
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: discounts
spec:
  to:
    kind: Service
    name: discounts
    weight: 100
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  port:
    targetPort: 8080