# values for discounts
replicaCount: 1

image:
  repository: quay.io/dseveria/discounts
  tag: v1.0.1
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

service:
  port: 8080
  targetPort: 8080
  type: ClusterIP

route:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  wildcardPolicy: None

configmap:
  application:
    colour: black
    mode: online
    version: v1.0.1
  quarkus:
    log:
      level: debug