# values for discounts
replicaCount: 1

image:
  repository: quay.io/dseveria/discounts
  tag: v1.0.1
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

service:
  port: 8080
  targetPort: 8080

route:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge

configmap:
  data:
    application.colour: black
    application.mode: online
    application.version: v1.0.1
    quarkus.log.level: debug